---
- set_fact:
    instance_id: "{{ item }}"

- name: "Set up for Wildfly instance {{ instance_id }}"
  include_role:
    name: wildfly_systemd
  vars:
    wildfly_home: "{{ wildfly.home }}"
    wildfly_user: "{{ wildfly.user }}"
    wildfly_group: "{{ wildfly.group }}"
    wildfly_config_base: "{{ wildfly.config.base }}"
    wildfly_basedir_prefix: "/opt/{{ inventory_hostname }}"
    wildfly_config_name: "{{ inventory_hostname }}"
    wildfly_instance_name: "{{ inventory_hostname }}"
    instance_id: "{{ item }}"
    service_systemd_env_file: "/etc/eap-{{ item }}.conf"
    service_systemd_conf_file: "/usr/lib/systemd/system/{{ inventory_hostname }}-{{ item }}.service"

- name: "Install RHSSO Extension on instance {{ instance_name }}"
  include_tasks: keycloak/keycloak-extension-install.yml

- name: "Deploy app on instance {{ instance_name }}"
  include_tasks: fine-tuned-wildfly.yml
