---
- ansible.builtin.assert:
    that:
      - wildfly is defined
      - wildfly.config is defined
      - wildfly.config.name is defined
      - wildfly.basedir_prefix is defined
      - wildfly.home is defined
      - nb_instance_by_node is defined
    quiet: true

- name: 'Stop all Wildfly instances'
  ansible.builtin.include_tasks: uninstall/stop_service.yml
  loop: "{{ range(1, (nb_instances|int + 1)) | list }}"

- name: "Delete all runtime and configuration files"
  ansible.builtin.include_tasks: uninstall/delete_files.yml
  loop: "{{ range(1, (nb_instances|int + 1)) | list }}"

- name: "Perform daemon-reload to ensure all services are removed"
  ansible.builtin.systemd:
    daemon_reload: yes

- name: "Uninstall Wildfly binaries"
  ansible.builtin.file:
    state: absent
    path: "{{ wildfly.home }}"
