---
- assert:
    that:
      - httpd is defined
      - httpd.user is defined
      - httpd.user.name is defined
      - httpd.group is defined
      - httpd.group.name is defined
      - httpd.home is defined
    quiet: true

- name: Create group
  ansible.builtin.group:
    name: "{{ httpd.group.name }}"
    state: present
    gid: "{{ httpd.group.id | default(omit) }}"

- name: Create user
  ansible.builtin.user:
    name: "{{ httpd.user.name }}"
    state: present
    uid: "{{ httpd.user.id | default(omit) }}"

- name: Change file ownership
  ansible.builtin.file:
    path: "{{ httpd.home }}"
    owner: "{{ httpd.user.name }}"
    group: "{{ httpd.group.name }}"
    recurse: true
  changed_when: false

- ansible.builtin.set_fact:
    zip_file_repo: /opt/apps

- name: Create repo directory
  ansible.builtin.file:
    path: "{{ zip_file_repo }}"
    state: directory

- stat:
    path: "{{ httpd.home }}/httpd"
  register: httpd_home

- name: Unarchive JBoss Core Services
  ansible.builtin.unarchive:
    src: "{{ zip_file_repo }}/jbcs.zip"
    remote_src: yes
    dest: /opt
  when:
    - not httpd_home.stat.exists

- name: "Post install HTTPD"
  ansible.builtin.command:
    cmd: "{{ httpd.home }}/httpd/.postinstall.systemd"
    chdir: "{{ httpd.home }}/httpd/"
    creates: /usr/lib/systemd/system/jbcs-httpd24-httpd.service

- name: "Ensures JBCS configuration is correct"
  ansible.builtin.template:
    src: templates/httpd.conf.j2
    dest: /opt/jbcs-httpd24-2.4/httpd/conf/httpd.conf
  notify:
    - "Restart JBCS"

- name: "Start HTTPd Service"
  ansible.builtin.service:
    name: jbcs-httpd24-httpd.service
    state: started
    enabled: yes

- name: "Wait for all used ports to be open"
  ansible.builtin.wait_for:
    port: "{{ item }}"
    delay: 0
  loop:
    - 80
    - 6666
  when:
    - check_jbcs_port is defined
