---
- name: 'expire mod_cluster cache and restart'
  become: true
  block:
    - ansible.builtin.assert:
        that:
          - httpd is defined
          - httpd.home is defined
          
    - name: Stop jbcs-httpd24-httpd service
      ansible.builtin.service:
        name: jbcs-httpd24-httpd.service
        state: stopped

    - name: Modify the settings  
      ansible.builtin.command: rm -rf {{ httpd.home }}/httpd/cache/mod_cluster/
    
    - name: Start jbcs-httpd24-httpd service 
      ansible.builtin.service:
        name: jbcs-httpd24-httpd.service
        state: started
