---
- name: "Ensures required packages are installed"
  ansible.builtin.include_role:
    name: flange_fastpackages
  vars:
    packages_list:
      - mailcap
      - unzip
      - firewalld

- name: "Ensure that firewalld service is running"
  become: yes
  ansible.builtin.systemd:
    name: firewalld
    enabled: yes
    state: started
