---
- name: "Fine tuning configuration: {{ instance_name }}"
  jcliff:
    wfly_home: "{{ wildfly.home }}"
    rule_file: roles/3trains_wildfly/files/custom/
    timeout: 7000
    management_port: "{{ wildfly_instance_management_port }}"
    components:
      - system_properties:
        - name: JBOSS_ID
          value: "{{ instance_name }}"
      - deployments:
          - name: info-1.0.war
            path: /opt/info-1.0.war
      - drivers:
          - driver_name: postgresql
            driver_module_name: org.postgresql
            driver_class_name: org.postgresql.Driver
            driver_xa_datasource_class_name: org.postgresql.xa.PGXADataSource
      - datasources:
          - name: "{{ instance_name }}db"
            use_java_context: 'true'
            jndi_name: "java:jboss/datasources/{{ postgres.db_name }}"
            connection_url: "jdbc:postgresql://{{ (groups['pgsql'][0] if groups['pgsql'] | length > 0 else 'localhost') }}:5432/{{ postgres.db_name }}"
            driver_name: postgresql
            user_name: "{{ postgres.user.name }}"
            password: "{{ postgres.user.password }}"
      - modcluster:
          proxy:
            - name: default
              proxies:
                - proxy1
  environment:
    JAVA_HOME: "{{ java.home }}"
  when:
    - not skip_jcliff is defined
