---
wildfly:
  home: "{{ override_wildfly_home | default('/opt/jboss-eap-7.3/') }}"
  user: wildfly
  group: wildfly
  config:
    base: standalone.xml
    name: jboss-eap.xml
postgres:
  db_name: wildfly
  user:
    name: wildfly
    password: wildfly
eap_instance_name: "{{ override_eap_instance_name | default('jboss-eap') }}"
workdir: /opt
app_repository: "{{ workdir }}/apps/"
gdrive_url: 'https://drive.google.com/uc?export=download&id='
app_url: "{{ gdrive_url }}1w9ss5okctnjUvRAxhPEPyC7DmbUwmbhb"
app_name: info
app_version: 1.1
app_dir: /opt/apps/
wfly_version: 19.0.0.Final
