---
collections:
  - name: middleware_automation.jcliff
    version: ">=0.0.21"
  - name: middleware_automation.redhat_csp_download
    version: ">=1.2.1"
  - name: middleware_automation.infinispan
    version: ">=0.1.6"
  - name: middleware_automation.keycloak
    version: ">=0.2.3"
  - name: middleware_automation.wildfly
    version: ">=0.0.5"
  - name: community.general
  - name: community.postgresql
