- name: "Download a demo app to deploy"
  get_url:
    url: "{{ app_url }}"
    dest: "{{ app }}"

- jcliff:
    wfly_home: "{{ wildfly.home }}"
    management_port: "{{ 9990 + ((item - 1) * 100) }}"
    subsystems:
      - system_props:
          - name: jcliff.enabled
            value: 'enabled.plus'
      - deployments:
          - artifact_id: sample.war
            name: sample
            path: "{{ app }}"
      - drivers:
          - driver_name: postgresql
            driver_module_name: org.postgresql
            driver_class_name: org.postgresql.Driver
            driver_xa_datasource_class_name: org.postgresql.xa.PGXADataSourcer
#          - datasources:
#              - name: ExampleDS2
#                use_java_context: 'true'
#                jndi_name: java:jboss/datasources/ExampleDS2
#                connection_url: "jdbc:h2:mem:test2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
#                driver_name: h2
