- name: "Download a demo app to deploy"
  get_url:
    url: "{{ app_url }}"
    dest: "{{ app }}"

- name: "Fine tune Wildfly configuration"
  jcliff:
    wfly_home: "{{ wildfly.home }}"
    management_port: "{{ 9990 + ((item - 1) * 100) }}"
    subsystems:
      - system_props:
          - name: jcliff.enabled
            value: 'enabled.plus'
      - deployments:
          - artifact_id: sample.war
            name: sample
            path: "{{ app }}"
      - drivers:
          - driver_name: postgresql
            driver_module_name: org.postgresql
            driver_class_name: org.postgresql.Driver
            driver_xa_datasource_class_name: org.postgresql.xa.PGXADataSourcer
          - datasources:
              - name: "{{ wildfly.config_name_prefix }}db"
                use_java_context: 'true'
                jndi_name: "java:jboss/datasources/{{ wildfly.config_name_prefix }}db"
                connection_url: "jdbc:postgresql://localhost:5432/{{ wildfly.config_name_prefix }}db"
                driver_name: postgresql
                user_name: "{{ wildfly.user }}"
                password: "{{ wildfly.user }}"
