- set_fact: package_name=postgresql-server
- name: Install PostgreSQL
  import_tasks: tasks/rpminfo.yml

- name: Init PostgesQL Db
  command:
    cmd: /usr/bin/postgresql-setup initdb
    creates: /var/lib/pgsql/data
  register: datadir_init

- name: Ensure the PostgreSQL service is running
  service:
    name: postgresql
    state: started
    enabled: yes
  when: datadir_init is success
