---
- assert:
    that:
      - wildfly is defined
      - wildfly.home is defined
    quiet: true
- set_fact:
    app_filename: "{{ app_name }}-{{ app_version }}.war"

- get_url:
    url: "{{ app_url }}"
    dest: "{{ app_dir }}/{{ app_filename }}"

- name: "Install Postresql driver"
  include_role:
    name: wildfly_driver
    tasks_from: jdbc_driver.yml
  vars:
      wildfly_user: "{{ wildfly.user }}"
      jdbc_driver_module_dir: "{{ wildfly.home }}//modules/org/postgresql/main"
      jdbc_driver_version: "{{ override_pgsql_jdbc_driver_version | default('9.2-1002-jdbc4') }}"
      jdbc_driver_jar_filename: "postgresql-{{ jdbc_driver_version }}.jar"
      jdbc_driver_jar_url: "https://repo.maven.apache.org/maven2/org/postgresql/postgresql/{{ jdbc_driver_version }}/{{ jdbc_driver_jar_filename }}"
      jdbc_driver_jar_installation_path: "{{ jdbc_driver_module_dir }}/{{ jdbc_driver_jar_filename }}"
      jdbc_driver_module_name: 'org.postgresql'

- wait_for:
    port: 9990

- name: "Fine tuning configuration: {{ instance_name | default('localhost') }}"
  jcliff:
    wfly_home: "{{ wildfly.home }}"
    timeout: 7000
    components:
      - system_properties:
        - name: JBOSS_ID
          value: "{{ instance_name }}"
      - drivers:
          - driver_name: postgresql
            driver_module_name: org.postgresql
            driver_class_name: org.postgresql.Driver
            driver_xa_datasource_class_name: org.postgresql.xa.PGXADataSource
      - datasources:
          - name: "{{ instance_name }}db"
            use_java_context: 'true'
            jndi_name: "java:jboss/datasources/{{ postgres.db_name }}"
            connection_url: "jdbc:postgresql://{{ (groups['pgsql'][0] if groups['pgsql'] | length > 0 else 'localhost') }}:5432/{{ postgres.db_name }}"
            driver_name: postgresql
            user_name: "{{ postgres.user.name }}"
            password: "{{ postgres.user.password }}"
      - deployments:
          - name: "{{ app_filename }}"
            path: "{{ app_dir }}/{{ app_filename }}"
  notify:
    - "Restart service JBoss EAP"

- wait_for:
    timeout: 10

- wait_for:
    port: 8080
