---
- ansible.builtin.set_fact:
    demo_app_redirect_uris: []
    origin_host: localhost

- name: Use loadbalancer as origin when defined
  ansible.builtin.set_fact:
    origin_host: "{{ groups['jbcs'][0] }}"
  when: groups['jbcs'] is defined and groups['jbcs'][0]|length > 0

- ansible.builtin.include_tasks: demo_urls_redirects/main.yml

- ansible.builtin.set_fact:
    keycloak_flange_client: "{{ keycloak_flange_client | combine ( { 'web_origins': demo_app_redirect_uris, 'redirect_uris': 'https://'+origin_host+demo_app_endpoint+'/*' } ) }}"

- name: Create demo realm and client
  ansible.builtin.include_role:
    name: keycloak_realm
  vars:
    keycloak_realm: "{{ keycloak_flange_realm }}"
    keycloak_clients:
      - "{{ keycloak_flange_client }}"
    keycloak_users: "{{ keycloak_flange_users }}"
