---
- ansible.builtin.assert:
    that:
      - item is defined
      - app_servers_list is defined
    quiet: true

- ansible.builtin.set_fact:
    app_list_by_instance: []

- ansible.builtin.set_fact:
    url: "https://{{ item }}"

- ansible.builtin.include_tasks: demo_app_all_urls_by_host.yml

- ansible.builtin.set_fact:
    app_servers_list: "{{ app_servers_list }} + {{ app_list_by_instance }}"
