---
- include_tasks: prereqs.yml
- include_tasks: install-jb-httpd.yml

- name: configure firewall for JBCS ports
  become: yes
  firewalld:
    port: "{{ port }}"
    permanent: true
    state: enabled
    immediate: yes
  loop:
    - "80/tcp"
    - "6666/tcp"
  loop_control:
    loop_var: port
