---
- name: "Ensures required packages are installed"
  include_role:
    name: 3trains_fastpackages
  vars:
    packages_list:
      - mailcap
      - unzip
      - firewalld

- name: "Ensure that firewalld service is running"
  systemd:
    name: firewalld
    enabled: yes
    state: started
