---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: Install required packages
      ansible.builtin.yum:
        use_backend: dnf
        name: "{{ item }}"
        state: present
      loop:
        - sudo
        - iproute
        - net-tools
        - bind-utils
        - glibc-locale-source
        - glibc-langpack-en
        - iproute
        - python3-lxml

    - name: Upgrade systemd (for postgres)
      ansible.builtin.dnf:
        name: systemd
        state: latest

    - ansible.builtin.file:
        state: directory
        path: "/opt/keycloak/keycloak-{{ keycloak_version }}/standalone/configuration"
