---
- ansible.builtin.assert:
    that:
      - wildfly is defined
      - wildfly.port_range_offset is defined
      - wildfly.home is defined
      - keycloak_download_url is defined
    quiet: true

- ansible.builtin.set_fact:
    wildfly_instance_port: "{{ 9990 + (item * 100) }}"

- ansible.builtin.set_fact:
    jboss_cli: "{{ wildfly.home }}/bin/jboss-cli.sh -c --controller=localhost:{{ wildfly_instance_port }}"

- name: "Wait for wildfly port {{wildfly_instance_port|int}}"
  ansible.builtin.wait_for:
    port: "{{wildfly_instance_port|int}}"
    host: localhost
    connect_timeout: 3
    delay: 5
    timeout: 60
  when:
    - rhn_username is defined

- block:
    - name: Check if Keycloak extensions installed
      ansible.builtin.command: >
        {{ jboss_cli }} --command='/extension=org.keycloak.keycloak-adapter-subsystem:read-resource'
      args:
        chdir: "{{ wildfly.home }}"
      changed_when: false
  rescue:
    - name: Install Keycloak Adapter and Reload
      block:
        - name: Install Keycloak Adapter
          ansible.builtin.command: >
            {{ jboss_cli }} --file={{ wildfly.home }}/bin/adapter-elytron-install.cli
          args:
            chdir: "{{ wildfly.home }}"
          changed_when: true
        - name: Reload After Keycloak Adapter Install
          ansible.builtin.command: >
            {{ jboss_cli }} --command=":reload"
          args:
            chdir: "{{ wildfly.home }}"
  when:
    - not disable_keycloak
    - rhn_username is defined
  throttle: 1
