---
- set_fact:
    port_shift: "{{ (item - wildfly.port_range_offset) * 100) }}"
- set_fact:
    wildfly_instance_management_port: "{{ 9990 + port_shift }}"
    wildfly_instance_http_port: "{{ 8080 + port_shift }}"
    wildfly_instance_https_port: "{{ 8443 + port_shift }}"
    wildfly_instance_ajp_port: "{{ 8009 + port_shift }}"

- name: configure firewall for Wildfly ports
  become: yes
  firewalld:
    port: "{{ port }}"
    permanent: true
    state: enabled
    immediate: yes
  loop:
    - "{{ wildfly_instance_http_port }}/tcp"
    - "{{ wildfly_instance_https_port }}/tcp"
    - "{{ wildfly_instance_ajp_port }}/tcp"
  loop_control:
    loop_var: port

- name: Set application detail
  set_fact:
    app_detail: "{{ apps | selectattr('version','equalto', sample_app_version) | list | first }}"

- name: Set Application Destination Directory
  set_fact:
    app_dest: "{{ app_dir + '/' + app_detail.name + '-' + app_detail.version + '.' + app_detail.extension }}"

- stat:
    path: "{{ app_dest }}"
  register: app_dest_path

- name: "Download a demo app to deploy"
  get_url:
    url: "{{ app_detail.url }}"
    dest: "{{ app_dest }}"
  when:
    - app_dest_path is defined
    - app_dest_path.stat is defined
    - not app_dest_path.stat.exists

- name: "Download a info app to deploy"
  get_url:
    url: "http://people.redhat.com/~rpelisse/info-1.1.war"
    dest: "/opt/info-1.1.war"
  when:
    - info_app is defined

- include_tasks: keycloak-configuration.yml
  when:
    - not disable_keycloak is defined

- include_tasks: jcliff/jcliff-with-keycloak.yml
  when:
    - not disable_keycloak is defined

- include_tasks: jcliff/jcliff-without-keycloak.yml
  when:
    - disable_keycloak is defined

- debug:
    msg: "nb_instance_by_node: {{ nb_instances }}"
