---

- name: "Install Prerequisites"
  include_tasks: prereqs.yml

- name: "Install Widfly"
  include_tasks: install-wildfly.yml

- name: "Install Postresql driver"
  include_tasks: pgsql_jdbc_driver.yml

- set_fact:
    nb_instances: "{{ (nb_instance_by_node | default(3) ) }}"

- set_fact:
    nb_instances: "{{ (nb_instances | int) +1 }}"

- include_tasks: appserver.yml
  loop: "{{ range(1, nb_instances|int) | list }}"
