---

- name: "Install Prerequisites"
  include_tasks: prereqs.yml

- name: "Install Widfly"
  include_tasks: install-wildfly.yml

- name: "Install Postresql driver"
  include_tasks: pgsql_jdbc_driver.yml

- include_tasks: appserver.yml
  loop: "{{ range(1, 4)|list }}"
