---

- set_fact:
    packages_list:
    - zip
    - unzip
    # - gcc
    # - redhat-rpm-config
    - procps-ng
    - initscripts
    - "{{ jvm_package | default('java-1.8.0-openjdk-devel') }}"

- name: "Ensures required packages are installed"
  include_role:
    name: 3trains_fastpackages

- name: install firewalld
  become: yes
  package:
    name: firewalld

- name: enable and start the firewalld service
  become: yes
  systemd:
    name: firewalld
    enabled: yes
    state: started

- name: "Create repo for custom rulesdir"
  file:
    path: /etc/jcliff
    state: directory

- name: "Deploy custom jcliff custom ruleset"
  copy:
    dest: /etc/jcliff/
    src: files/custom/remote_sockets.jcliff.yml

- name: Add missing rules to jcliff ruleset
  copy:
    src: "{{ item }}"
    dest: "{{ jcliff_rules_dir }}"
  loop:
    - files/rules/modcluster
    - files/rules/standard-sockets

- name: Update jcliff ruleset to add modcluster and keycloak
  copy:
    src: files/rules/rules
    dest: "{{ jcliff_rules_dir }}/rules"
