---
---
- name: "Install Red Hat Data Grid"
  include_role:
    name: infinispan

- name: "Configure firewalld for Red Hat Data Grid"
  include_role:
    name: infinispan
    tasks_from: firewalld.yml

- name: "Create kitchensink cache"
  include_role:
    name: infinispan
    tasks_from: cache.yml
  vars:
    jdg_url: "http://localhost:11222"
    jdg_username: 'supervisor'
    jdg_password: "{{ supervisor_password }}"
    cache:
      name: kitchensink_sql_cache
