---
# tasks file for keycloak

- name: Include keycloak install role
  include_role:
    name: keycloak
    vars:
      keycloak_admin_password: "{{ admin_password }}"

- name: Include keycloak firewall tasks
  include_role:
    name: keycloak
    tasks_from: firewalld

- include_tasks: demo_urls_redirects/main.yml

- set_fact:
    keycloak_3trains_realm: "{{{ keycloak_3trains_realm | combine ( { web_origins: demo_app_redirect_uris } ) }}"

- name: Create demo realm and client
  include_role:
    name: keycloak
    tasks_from: manage_realm.yml
    vars:
      keycloak_admin_password: "{{ admin_password }}"
      keycloak_realm: "{{ keycloak_3trains_realm }}"
      keycloak_clients:
        - "{{ keycloak_3trains_client }}"
      keycloak_users: "{{ keycloak_3trains_users }}"
