---

- name: "Get User {{ user.username }}"
  uri:
    url: "{{ keycloak_url }}/auth/admin/realms/{{ keycloak_realm }}/users?username={{ user.username }}"
    headers:
      validate_certs: no
      Authorization: "Bearer {{ keycloak_auth_response.json.access_token }}"
  register: keycloak_user

- name: "Manage Client Role Mapping for {{ user.username }}"
  include_tasks: manage_user_client_roles.yml
  loop: "{{ user.client_roles | flatten }}"
  loop_control:
    loop_var: client_role
