---
- name: "Restart service JBoss EAP"
  systemd:
    state: restarted
    name: "{{ instance_name }}"

- name: "Stop service JBoss EAP"
  systemd:
    state: stopped
    name: "{{ instance_name }}"
