---
- name: "reload systemd unit"
  ansible.builtin.systemd:
    daemon_reload: yes

- name: "restart postgres"
  ansible.builtin.service:
    name: postgresql
    no_block: True
    state: restarted

- block:
    - name: "wait for postgres port"
      ansible.builtin.wait_for:
        port: 5432
        delay: 5
        timeout: 15
  rescue:
    - name: "force stop postgresql https://access.redhat.com/solutions/5605181"
      ansible.builtin.command: systemctl daemon-reexec
    - name: "restart postgres"
      ansible.builtin.service:
        name: postgresql
        state: restarted
