---
- assert:
    that:
      - nb_instances is defined
    quiet: true

- set_fact:
    demo_app_redirect_uris: []

- set_fact:
    demo_app_redirect_uris: "{{ demo_app_redirect_uris + item }}"
  loop:
    - [ "https://{{ (groups['jbcs'][0] if groups['jbcs'] | length > 0 else 'localhost') }}{{ demo_app_endpoint }}/*"]

- set_fact:
    app_servers_list: []

- include_tasks: demo_app_urls.yml
  with_items:
    - "{{ groups['wildfly'] }}"

- set_fact:
    demo_app_redirect_uris: "{{ demo_app_redirect_uris }} + ['{{ item }}{{ demo_app_endpoint }}/*']"
  with_items:
    - "{{ app_servers_list }}"

- debug:
    msg: "demo_app_redirect_uris: {{ demo_app_redirect_uris }}"
  when:
    - debug_redirects_urls is defined
