---

admin_password: "redhat1!"

keycloak_ha_enabled: True

reverse_proxy_url: jbcs-0

infinispan_user: supervisor
infinispan_pass: itsme
infinispan_url: jdg-1

postgres_jdbc_url: jdbc:postgresql://pgsql-0:5432/keycloak
postgres_db_user: keycloak-user
postgres_db_pass: keycloak-pass


# Demo Realm and App
keycloak_3trains_realm: 3trains
keycloak_3trains_client_name: 3trains
keycloak_3trains_admin_role: 3trainsadmin
keycloak_3trains_user_role: 3trainsuser

demo_app_host: "{{ trains_app_host | default('localhost') }}"
demo_app_endpoint: "{{ train_app_endpoint | default('/kitchensink') }}"
keycloak_3trains_client:
  name: "{{ keycloak_3trains_client_name }}"
  roles:
    - "{{ keycloak_3trains_user_role }}"
    - "{{ keycloak_3trains_admin_role }}"
  realm: "{{ keycloak_3trains_realm }}"
  public_client: True
  web_origins: '+'

keycloak_3trains_users:
  - username: 3trainsadmin
    password: password
    client_roles:
      - client: "{{ keycloak_3trains_client_name }}"
        role: "{{ keycloak_3trains_admin_role }}"
        realm: "{{ keycloak_3trains_realm }}"
      - client: "{{ keycloak_3trains_client_name }}"
        role: "{{ keycloak_3trains_user_role }}"
        realm: "{{ keycloak_3trains_realm }}"
  - username: 3trainsuser
    password: password
    client_roles:
      - client: "{{ keycloak_3trains_client_name }}"
        role: "{{ keycloak_3trains_user_role }}"
        realm: "{{ keycloak_3trains_realm }}"
