---
- ansible.builtin.import_playbook: preconds.yml

# PGSL Playbook
- ansible.builtin.import_playbook: postgresql.yml

# JBoss Core Services (Apache HTTPD)
#- import_playbook: jbcs.yml

# Datagrid Playbook
- ansible.builtin.import_playbook: jdg.yml

# Keycloak Playbook
- ansible.builtin.import_playbook: keycloak.yml

# Wildfly Playbook
- ansible.builtin.import_playbook: wildfly.yml
