---
- name: Playbook for EAP hosts
  hosts: eap
  vars:
    eap_software_id: "{{ upgrade_eap_software_id | default('80101') }}"
    eap_zipfile: "{{ app_repository }}/eap-{{ eap_software_id }}.zip"
    rhn_eap_download_url: "https://access.redhat.com/jbossnetwork/restricted/softwareDownload.html?softwareId={{ eap_software_id }}"
  tasks:
    - name: EAP cleanup
      include_role:
        name: 3trains_eap
        tasks_from: uninstall_eap.yml
