---
- name: Playbook for EAP hosts
  hosts: eap
  collections:
    - middleware_automation.redhat_csp_download
    - middleware_automation.jcliff
  roles:
    - redhat_csp_download
    - jcliff
  vars:
    eap_software_id: "{{ upgrade_eap_software_id | default('80101') }}"
    eap_zipfile: "{{ app_repository }}/eap-{{ eap_software_id }}.zip"
    rhn_eap_download_url: "https://access.redhat.com/jbossnetwork/restricted/softwareDownload.html?softwareId={{ eap_software_id }}"
  tasks:
    - name: EAP
      include_role:
        name: 3trains_eap

    - meta: flush_handlers

    - wait_for:
        port: 8080

    - include_role:
        name: 3trains_eap
        tasks_from: check.yml
      loop:
        - java.runtime.version
        - 'WFLYSRV0025: JBoss EAP'

