---
- name: Playbook for Wildfly Hosts
  hosts: jbcs
  collections:
    - middleware_automation.redhat_csp_download
  roles:
    - redhat_csp_download
  tasks:
    - name: "JBoss Core Services"
      include_role:
        name: 3trains_jbcs
