---
- name: Playbook for JBCS Hosts
  hosts: jbcs
  collections:
    - middleware_automation.redhat_csp_download
  roles:
    - redhat_csp_download
  tasks:
    - name: "JBoss Core Services"
      include_role:
        name: flange_jbcs
