---
- name: Playbook for JDG Hosts
  hosts: jdg
  collections:
    - middleware_automation.redhat_csp_download
    - middleware_automation.infinispan
  roles:
    - redhat_csp_download
  tasks:
    - name: "Install Red Hat Data Grid"
      include_role:
        name: infinispan
      vars:
        infinispan_users: "{{ user_accounts }}"
        supervisor_password: "{{ admin_pass }}"

    - name: "Configure firewalld for Red Hat Data Grid"
      include_role:
        name: infinispan
        tasks_from: firewalld.yml

    - name: "Create kitchensink cache"
      include_role:
        name: infinispan
        tasks_from: cache.yml
      vars:
        jdg_username: supervisor
        jdg_password: "{{ admin_pass }}"
        cache:
          name: kitchensink_sql_cache