---
- name: Playbook for JDG Hosts
  hosts: jdg
  collections:
    - middleware_automation.redhat_csp_download
    - middleware_automation.infinispan
  roles:
    - redhat_csp_download
    - role: infinispan
      supervisor_password: "{{ admin_pass }}"
      infinispan_users: "{{ user_accounts }}"
    - role: infinispan_cache
      deployer_password: "{{ admin_pass }}"
      cache_xml: >
           <local-cache name="kitchensink_sql_cache" statistics="true">
             <encoding media-type="application/x-protostream"/>
           </local-cache>
