---
- name: Playbook for JDG Hosts
  hosts: jdg
  become: yes
  collections:
    - middleware_automation.redhat_csp_download
    - middleware_automation.infinispan
  roles:
    - redhat_csp_download
  tasks:
    - set_fact:
        override_jdg_bind_address: "{{ ansible_nodename }}"
    - name: "JDG"
      include_role:
        name: 3trains_jdg
