---
- name: Playbook for Keycloak Hosts
  hosts: keycloak
  collections:
    - middleware_automation.redhat_csp_download
    - middleware_automation.keycloak
  roles:
    - redhat_csp_download
    - role: keycloak
      keycloak_admin_password: "{{ admin_pass }}"
    - role: flange_keycloak
      keycloak_admin_password: "{{ admin_pass }}"
      keycloak_clients:
        - "{{ keycloak_flange_client }}"
