---
- name: Playbook for Keycloak Hosts
  hosts: keycloak
  collections:
    - middleware_automation.redhat_csp_download
  roles:
    - redhat_csp_download
    - name: keycloak
      keycloak_admin_password: "{{ admin_pass }}"
  tasks:
    - name: Keycloak Role
      include_role:
        name: flange_keycloak
      vars:
        keycloak_admin_password: "{{ admin_pass }}"
        keycloak_clients:
          - "{{ keycloak_flange_client }}"
