---
- name: Playbook for keycloak Hosts
  hosts: keycloak
  collections:
    - middleware_automation.infinispan
  tasks:
    - name: keycloak restart
      include_role:
        name: keycloak
        tasks_from: restart_keycloak.yml
