---
- name: Playbook for Wildfly Hosts
  hosts: wildfly
  tasks:

    - set_fact:
        nb_instances: "{{ (nb_instance_by_node | default(2) ) }}"

    - include_tasks: roles/3trains_wildfly/tasks/status.yml
      loop: "{{ range(1, (nb_instances|int + 1)) | list }}"
