---
- name: Playbook for Wildfly Hosts
  hosts: wildfly
  tasks:

    - ansible.builtin.set_fact:
        nb_instances: "{{ (nb_instance_by_node | default(2) | int ) }}"

    - name: Wildfly Role
      ansible.builtin.include_role:
        name: flange_wildfly
        tasks_from: uninstall_wfly_instance.yml
