---
- name: Playbook to update Applications on a Wildfly instance
  hosts: wildfly
  become: true
  tasks:
    - name: Wildfly Role
      ansible.builtin.include_role:
        name: flange_wildfly
        tasks_from: fine-tuned-wildfly.yml
      vars:
        keycloak_flange_url: "{{ 'http://' + (groups['keycloak'][0] if groups['keycloak']| length > 0 else 'localhost')  + ':8080' }}"
      loop: "{{ range(1, 4)|list }}"
