---
- name: Playbook for Wildfly Hosts
  hosts: wildfly
  collections:
    - middleware_automation.jcliff
    - middleware_automation.wildfly
    - middleware_automation.redhat_csp_download
  roles:
    - redhat_csp_download
    - jcliff
    - flange_wildfly
