---
name: CI
"on":
  push:
    branches:
      - master
  pull_request:
  repository_dispatch:

env:
  COLORTERM: 'yes'
  TERM: 'xterm-256color'
  PYTEST_ADDOPTS: '--color=yes'

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.9"]
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      
      - name: Install yamllint, ansible and molecule
        run: |
          python -m pip install --upgrade pip
          pip install ansible-base==2.10.17 yamllint 'molecule[docker]~=3.5.2' ansible-compat==2.0.2 ansible-core netaddr flake8 ansible-lint voluptuous
          pip install -r requirements.txt

      - name: Create default collection path
        run: |
          mkdir -p /home/runner/.ansible/collections/ansible_collections

      - name: Install ansible-lint custom rules
        uses: actions/checkout@v2
        with:
          repository: ansible-middleware/ansible-lint-custom-rules
          path: ansible_collections/ansible-lint-custom-rules/

      - name: Run molecule test
        run: molecule test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
