---
- ansible.builtin.set_fact:
    update_cache: true
    packages_to_install: []

- name: "Check packages to be installed"
  ansible.builtin.include_tasks: tasks/build-packages-list-to-install.yml
  loop: "{{ packages_list | flatten }}"
  loop_control:
    loop_var: package_name

- name: "Install packages: {{ packages_to_install }}"
  become: yes
  ansible.builtin.yum:
    name: "{{ packages_to_install }}"
    state: latest
  when: packages_to_install | length > 0
